name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Print npm version
      run: |
        npm --version
    - name: Clear npm cache
      run: |
        npm cache clean --force
    - name: Install dependencies
      run: |
        cd website
        npm ci
    - name: Build the app
      run: |
        cd website
        npm run build
    - name: Run the component test
      run: |
        cd website
        npm test
    - name: Start the app
      run: |
        cd website
        npm start &
        npx wait-on --timeout 60000
